/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#f9f9f9',
        'outline-variant': '#c3c8bf',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#dae6d1',
        'surface-container': '#eeeeee',
        'surface-dim': '#dadada',
        tertiary: '#545f4f',
        'surface-variant': '#e2e2e2',
        'surface-container-high': '#e8e8e8',
        'on-error-container': '#93000a',
        'on-background': '#1a1c1c',
        'surface-container-highest': '#e2e2e2',
        'surface-bright': '#f9f9f9',
        'tertiary-fixed-dim': '#becab6',
        'on-tertiary-fixed': '#141e11',
        'on-secondary-container': '#735f46',
        'on-secondary-fixed': '#261906',
        'secondary-fixed': '#f9debe',
        outline: '#747871',
        'on-primary-container': '#f7fff2',
        'inverse-primary': '#b6cdb2',
        'on-secondary-fixed-variant': '#55442c',
        'on-surface': '#1a1c1c',
        'on-tertiary-container': '#f8ffef',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f1f1f1',
        'tertiary-container': '#6c7866',
        'surface-container-low': '#f3f3f3',
        'on-tertiary-fixed-variant': '#3f4a3a',
        'secondary-fixed-dim': '#dcc3a4',
        primary: '#4c614c',
        'on-primary-fixed-variant': '#384c37',
        'on-primary-fixed': '#0d200f',
        'primary-fixed-dim': '#b6cdb2',
        'on-secondary': '#ffffff',
        surface: '#f9f9f9',
        'secondary-container': '#f6dcbb',
        'on-primary': '#ffffff',
        'inverse-surface': '#2f3131',
        'on-error': '#ffffff',
        'surface-tint': '#4f644e',
        'primary-fixed': '#d1e9cd',
        'primary-container': '#657a63',
        'on-tertiary': '#ffffff',
        secondary: '#6e5b42',
        'on-surface-variant': '#434842',
        error: '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'container-max': '1280px',
        'element-gap': '32px',
        'section-padding': '120px',
      },
      fontFamily: {
        'headline-xl': ['Newsreader', 'serif'],
        'display-lg': ['Newsreader', 'serif'],
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'headline-md': ['Newsreader', 'serif'],
        'label-caps': ['Manrope', 'sans-serif'],
        button: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.2', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '300' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1.2', letterSpacing: '0.1em', fontWeight: '600' }],
        button: ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
